const fs = require('fs');

const clinics = [
  { name: "10 years ago美容外科", account: "@10years_ago_jp" },
  { name: "1mm美容外科", account: "@1mmps_jp" },
  { name: "1パーセント整形外科", account: "@1percentps" },
  { name: "21美容外科", account: "@21psjp" },
  { name: "2YD（ヤンユンドル）口腔顎顔面外科", account: "@2yd_japan" },
  { name: "365mc", account: "@365mc_jp" },
  { name: "4月31日美容外科", account: "@april31jp" },
  { name: "AB美容外科", account: "@ABPRS_JP" },
  { name: "AM美容外科", account: "@amps_jp" },
  { name: "DU美容整形外科", account: "@dups_jp" },
  { name: "DDAY美容外科", account: "@ddaypsjapan" },
  { name: "DM美容外科", account: "@dm1004jp" },
  { name: "AND美容整形外科", account: "@and_ps_jp" },
  { name: "AND美容整形外科(目)", account: "@and_ps_eye" },
  { name: "ARC美容整形外科", account: "@ARC_ps_" },
  { name: "GIFT美容整形外科", account: "@giftpsjp" },
  { name: "BN (ビエヌ) 美容外科", account: "@somakisa222" },
  { name: "BT整形外科", account: "@BTps_jp" },
  { name: "CBK整形外科", account: "@CbkpsJ" },
  { name: "DA美容外科", account: "@daprsjp" },
  { name: "ES清潭", account: "@ES025406042" },
  { name: "HERSHE整形外科", account: "@HersheJapan" },
  { name: "IK美容整形外科", account: "@IKplasticjp" },
  { name: "EU口腔顎顔面外科", account: "@Eujapan2" },
  { name: "IQ美容整形外科", account: "@iqprsjp" },
  { name: "JAYJUN美容外科", account: "@jayjun_jpn" },
  { name: "JT整形外科", account: "@JTJPps" },
  { name: "KOKO美容外科", account: "@kokopsjp" },
  { name: "K美容整形外科病院", account: "@k_ps_jp" },
  { name: "MOOi整形外科", account: "@mooips_jp" },
  { name: "LAREE美容外科", account: "@lareeclinic" },
  { name: "FINT美容外科", account: "@FINT_jp" },
  { name: "MANO美容整形外科", account: "@MANO95421454" },
  { name: "NEAT美容外科", account: "@neatpsjp" },
  { name: "RSET美容外科", account: "@resetps" },
  { name: "MARQ (マーク) 美容外科", account: "@MARQ_PS" },
  { name: "Nスリム医院", account: "@nslimclinic" },
  { name: "NoseLab (ノーズラボ)", account: "@korea_glory" },
  { name: "newslim医院", account: "@newslim_jp" },
  { name: "NEWDAY美容整形外科", account: "@newdaypsjp" },
  { name: "SH整形外科", account: "@kshclinic" },
  { name: "SUI美容外科", account: "@suips1999" },
  { name: "SM整形外科", account: "@SM_official_jp" },
  { name: "SODA (ソーダ) 整形外科", account: "@sodaps_official" },
  { name: "タシピウム整形外科", account: "@dasipium" },
  { name: "TAKO美容整形外科", account: "@takoprs" },
  { name: "ダルム美容外科", account: "@dareum_jp" },
  { name: "The Door ザドア美容外科", account: "@thedoorps_jp" },
  { name: "THE MENTOR整形外科", account: "@mentorjp" },
  { name: "TJ美容外科", account: "@beautifultjps" },
  { name: "TOBE美容外科", account: "@tobeps_jp" },
  { name: "TT整形外科", account: "@TTps_jp" },
  { name: "U&U美容外科", account: "@_unups" },
  { name: "UcanB美容外科", account: "@ucanb_ps" },
  { name: "VAVA美容外科", account: "@VAVApsjpvava" },
  { name: "VGベリーグッド美容整形外科", account: "@VgprsJ" },
  { name: "VIBE美容外科", account: "@vibeprs" },
  { name: "VN美容外科", account: "@vnps_jp" },
  { name: "WANT美容外科", account: "@wantps_jp" },
  { name: "WAVE医院", account: "@bewavejp" },
  { name: "WHY口腔顎顔面外科", account: "@whyoms_jp" },
  { name: "WOOA美容外科", account: "@wooapr" },
  { name: "WOORI (ウリ) 美容外科", account: "@wooripsjp" },
  { name: "XO美容整形外科", account: "@xops_jp" },
  { name: "instar整形外科", account: "@instarjp" },
  { name: "id美容クリニック (ID)", account: "@idhospital_jp" },
  { name: "アイフィット整形外科", account: "@eyefit_kr" },
  { name: "アイティン美容整形外科", account: "@eyetingjp" },
  { name: "アイニーク美容外科", account: "@iniquejp" },
  { name: "アナザー整形外科", account: "@anotherpsjp" },
  { name: "アン美容外科", account: "@ahnps1004_jp" },
  { name: "アンサー美容外科", account: "@answerpsjp" },
  { name: "イッテム美容外科医院", account: "@Ittemps_jp" },
  { name: "アイルミ美容外科", account: "@ilumipsjp" },
  { name: "アーバン整形外科", account: "@prs_urban" },
  { name: "アウア美容外科", account: "@ourps_" },
  { name: "アウラ美容整形外科", account: "@auraps2024" },
  { name: "アバント (AVANT) 美容外科", account: "@avant_2022" },
  { name: "イブ整形外科", account: "@EvePlastic" },
  { name: "イエロー美容整形外科", account: "@yellowpsjp" },
  { name: "イウル整形外科", account: "@ieulps_jp" },
  { name: "イルチ整形外科（一致整形外科）", account: "@Dr_hyungsukmoon" },
  { name: "ウィーバー（UVERSE）美容整形外科", account: "@uverse_jp" },
  { name: "ウアイン整形外科", account: "@wooahinps_jp" },
  { name: "ウォンジン美容整形外科", account: "@wonjin_jpn" },
  { name: "エイト整形外科", account: "@8ightjp" },
  { name: "エイペックス美容整形外科", account: "@apex_surgery" },
  { name: "エートップ (Atop)", account: "@atopseikei" },
  { name: "エンプラス医院", account: "@nplus_jp" },
  { name: "ETONNE美容外科", account: "@ETONNE_jp" },
  { name: "オーサム美容整形外科", account: "@Ohsome_ps" },
  { name: "オヌル整形外科", account: "@onulpsjapan" },
  { name: "オネスティ美容外科", account: "@honestyps_jp" },
  { name: "オペラ整形外科", account: "@opera_ps_" },
  { name: "温度美容外科(オンド美容外科)", account: "@ondops_jp" },
  { name: "オルロ美容外科", account: "@olops_jp" },
  { name: "オンユ (ONYU) 美容外科", account: "@onyoops_jp" },
  { name: "オンリーアイ美容外科 (ONLY EYE美容外科)", account: "@onlyeye_jp" },
  { name: "ガーネット美容整形外科", account: "@garnetps_jp" },
  { name: "カスタム整形外科", account: "@customps1" },
  { name: "ギリン(GIRIN)整形外科", account: "@girinjp" },
  { name: "クラッシー美容外科", account: "@classypsjapan" },
  { name: "クリーヴ美容外科", account: "@clyvepsjp" },
  { name: "クッキー整形外科", account: "@cookipskorea" },
  { name: "クレア美容整形外科", account: "@clairps_jp" },
  { name: "コウェル美容外科", account: "@cwseikei" },
  { name: "グラム整形外科", account: "@glamps_jp" },
  { name: "グリダ美容外科", account: "@gridapsjp" },
  { name: "グナル (Gnal) 美容外科", account: "@geunal_jp" },
  { name: "グレイス整形外科", account: "@grc_vline" },
  { name: "グランド美容整形外科", account: "@grandps_jp" },
  { name: "グロービー美容整形外科", account: "@glovijapan" },
  { name: "ケイアート (K-ART) 整形外科", account: "@kartps3615" },
  { name: "コウォン (Cowon) 整形外科", account: "@prepost1" },
  { name: "コエンミ（旧ソウルクイーン）", account: "@seoulqueen7" },
  { name: "コード整形外科", account: "@codeps_jp" },
  { name: "ココライン美容外科", account: "@cocoline_nose" },
  { name: "コユ美容整形外科", account: "@koyoups_jp" },
  { name: "コビジュ医院", account: "@JPkobijou" },
  { name: "コーヘン (Cohen) 美容外科", account: "@cohenclinic" },
  { name: "サンキュー美容外科", account: "@thankyoups_jp" },
  { name: "ザビダン (The Vidan)", account: "@thebidanjp" },
  { name: "ザ・セロイ美容外科", account: "@theseroijp" },
  { name: "ザ・プラン美容整形外科", account: "@theplan_psjp" },
  { name: "ザ・プラス美容整形外科", account: "@theplusjapan" },
  { name: "ザ フェイス口腔顎顔面外科", account: "@thefacedental" },
  { name: "ザウェイ美容外科", account: "@thewayps" },
  { name: "ザスキニークリニック", account: "@theskinny46" },
  { name: "シークレット整形外科", account: "@secretpsm" },
  { name: "シウ美容整形外科", account: "@Siwoopsjp" },
  { name: "シウォン整形外科", account: "@SheOnePS" },
  { name: "シグネチャー美容外科", account: "@signaturepsps" },
  { name: "シャープ整形外科", account: "@sharpps_jp" },
  { name: "シュガー美容整形外科", account: "@sugarprs" },
  { name: "ジンダム美容外科", account: "@jindamps" },
  { name: "ジャスト美容整形外科", account: "@justprsjp" },
  { name: "ジュエリー美容外科", account: "@jewelrypsjapan" },
  { name: "スケッチ整形外科", account: "@Sketch_psjp" },
  { name: "スーンプラス美容整形外科", account: "@soonplusjp" },
  { name: "スリムエディション医院", account: "@slimededition" },
  { name: "スターライン整形外科", account: "@starlinejp" },
  { name: "スノウ医院", account: "@snowprsjp" },
  { name: "セギム美容整形", account: "@SaekimJP" },
  { name: "セイイエス医院", account: "@sayyesclinicjpn" },
  { name: "セミン整形外科", account: "@seminpsjapan" },
  { name: "セロ美容外科", account: "@saerops" },
  { name: "ソジン整形外科", account: "@seojin_ps" },
  { name: "ソンプム美容外科", account: "@sungpumps_jp" },
  { name: "チャミン美容外科", account: "@chaminps_jp" },
  { name: "チョンダムDEAR整形外科", account: "@dearpsjapan" },
  { name: "チョンダムOK整形外科", account: "@okaypsjpn" },
  { name: "チョイスライン医院", account: "@choiceline_jp" },
  { name: "チョウムチョロム美容外科", account: "@likefirst_jp" },
  { name: "チョンダムビョル美容整形外科", account: "@CheongdamStar" },
  { name: "テーラー (Tailor) 美容整形外科", account: "@TAILORPS1" },
  { name: "ディバイン美容整形外科", account: "@LINEID_divineps" },
  { name: "ディライトクリニック", account: "@delight_ps_jp" },
  { name: "ディテ美容外科", account: "@diteps_jp" },
  { name: "トップクラス美容外科", account: "@topclasspsjpn" },
  { name: "トップフェイス", account: "@topfacejp" },
  { name: "ドクター美", account: "@drmijp" },
  { name: "ドクタータク整形外科", account: "@dr_tak_ps" },
  { name: "ドレス美容外科", account: "@dressjp" },
  { name: "ドラマ美容外科", account: "@drama_psjp" },
  { name: "ナナ美容外科", account: "@nanahospital" },
  { name: "ナビ美容整形外科", account: "@NAVI_KOREA_" },
  { name: "ノ・ジョンフン整形外科", account: "@njhpsjp2023" },
  { name: "ノート美容外科", account: "@noteps_jp" },
  { name: "ハイボム美容外科", account: "@hivompsJP" },
  { name: "ハニ整形外科", account: "@hanips_jp" },
  { name: "バイウォン美容外科", account: "@BywonClinic" },
  { name: "バダ美容外科", account: "@BADApsjp" },
  { name: "バタン美容外科", account: "@batangjp" },
  { name: "バノバギ美容整形外科", account: "@banobagijapan" },
  { name: "バラボン整形外科", account: "@Varabon_JP" },
  { name: "バランスラボ美容外科医院", account: "@balancelabps" },
  { name: "バンニ美容外科", account: "@vannypsjp" },
  { name: "バナナ美容整形外科", account: "@bananaps__" },
  { name: "ボセルクリニック", account: "@BocelleS" },
  { name: "パスカル美容外科", account: "@shimmian_nose" },
  { name: "パラミクリニック", account: "@ParamiClinic" },
  { name: "ヒット (HIT) 整形外科", account: "@hitpsjp" },
  { name: "ヒューマン美容外科", account: "@humanpsjp" },
  { name: "ビューティーライン整形外科", account: "@beautylinejp" },
  { name: "ビューラベル美容整形外科", account: "@beulibal" },
  { name: "ビュー美容外科", account: "@kr_biyo_seikei" },
  { name: "ビユ美容外科", account: "@viuukorea" },
  { name: "ビリーフ整形外科", account: "@vlif_ps" },
  { name: "フィッティング医院", account: "@fittingclinicjp" },
  { name: "フォーレ美容外科", account: "@faure_1" },
  { name: "フェイスプラス整形外科", account: "@faceplusjp" },
  { name: "フェイスライン美容整形外科", account: "@faceline1004" },
  { name: "フルリュン美容外科", account: "@excellent_ps" },
  { name: "フレッシュホンドクター整形外科", account: "@freshps5512" },
  { name: "ブラウン整形外科", account: "@braunps_jp2" },
  { name: "プライベート美容外科", account: "@privateps_jp" },
  { name: "プラデン (PLADEN) 美容整形外科", account: "@PLADENPSJAPAN" },
  { name: "プラネット美容整形外科", account: "@planet_ps_ko" },
  { name: "プリ整形外科", account: "@vvlyps" },
  { name: "プリティ美容整形外科", account: "@prettypsjp" },
  { name: "プリンス整形外科", account: "@princepsjp" },
  { name: "ボムナゲ・ペークリニック", account: "@bbaebbae_jp" },
  { name: "ポップ POP 整形外科", account: "@POPJapanPS" },
  { name: "ボンディ美容整形外科", account: "@borndips" },
  { name: "マイティー美容整形外科", account: "@mightyps_jp" },
  { name: "ムードオン美容外科", account: "@onmood5" },
  { name: "マイン美容外科", account: "@jpmineplastic" },
  { name: "マーブル美容外科", account: "@marblepsjapan" },
  { name: "ミジャク美容外科", account: "@mijak_jp" },
  { name: "ミナ美容外科", account: "@minaps_japan" },
  { name: "ミント整形外科", account: "@mintpskr" },
  { name: "MIHO美容整形外科", account: "@Mihojapan2010" },
  { name: "ミラクル美容整形外科", account: "@miraclelifting" },
  { name: "メイドヤング美容外科", account: "@MadeYoung_japan" },
  { name: "メリー整形外科", account: "@Merryps_jp" },
  { name: "メイト整形外科", account: "@matepsjp" },
  { name: "ユニーク美容整形外科", account: "@unique__jp" },
  { name: "ユノ美容外科", account: "@Yunojp2" },
  { name: "ユボム (UVOM) 整形外科", account: "@uvom_" },
  { name: "ユー&リン美容整形外科", account: "@youandlin_jp" },
  { name: "ヨンセUP整形外科", account: "@YonseiupSeoul" },
  { name: "ラスト美容外科", account: "@LASTPSJP" },
  { name: "ライアン美容外科", account: "@JapanRyan" },
  { name: "ライク美容整形外科", account: "@lps3329" },
  { name: "ミュリー美容外科", account: "@muly_jp" },
  { name: "ラインカルチャー", account: "@lineculturejp" },
  { name: "ラインの正解", account: "@prettybody_line" },
  { name: "ラフォーレ美容外科", account: "@laforetjp" },
  { name: "ラビチェ医院", account: "@laviche_jp" },
  { name: "ラプリン美容外科 (Laprin)", account: "@Laprin_JP" },
  { name: "ラミチェ美容外科", account: "@Lamiche_Japan" },
  { name: "リアイ整形外科", account: "@lieyepsjp" },
  { name: "READY整形外科", account: "@READYPS_JP" },
  { name: "リア美容外科", account: "@reapsjp" },
  { name: "リーフ美容外科", account: "@Liffpsjp" },
  { name: "リウム（LIMO）", account: "@limops_jpn" },
  { name: "リエンジャン美容外科", account: "@lienjangjp" },
  { name: "リディアンクリニック", account: "@lydian_jp" },
  { name: "リフェイス口腔顎顔面外科", account: "@Reface_hs" },
  { name: "リスペック (Respec) 整形外科", account: "@respectps_jp" },
  { name: "リチャム美容整形外科", account: "@liftingreal2" },
  { name: "リティング美容外科（釜山院）", account: "@liting_japan" },
  { name: "リトマス美容整形外科", account: "@retmusps_jp" },
  { name: "リニュ整形外科", account: "@trnu2019" },
  { name: "リンク美容外科", account: "@kankokuseikei_" },
  { name: "ルロゼ医院", account: "@LE_ROSE_JP" },
  { name: "ルジェ美容外科", account: "@lejclinic" },
  { name: "ルーヴル美容外科", account: "@louvre__ps" },
  { name: "LUHO美容外科", account: "@luho_beauty_jp" },
  { name: "レアート整形外科", account: "@Lesarts_JP" },
  { name: "ログ美容整形外科", account: "@Logps_jp" },
  { name: "ロウェル美容整形外科", account: "@Lowellprs" },
  { name: "リターニング整形外科", account: "@jpreturning" },
  { name: "ローヤルライン医院", account: "@royallineclinic" },
  { name: "ワイヤング美容外科", account: "@youryoungpsjp" },
  { name: "ワナビー美容整形外科", account: "@WANNABE_JPN" },
  { name: "ワンダフル美容外科", account: "@wonderfulpsjpn" },
  { name: "ワーナ美容外科", account: "@wannaps_jp" },
  { name: "ビョル美容外科", account: "@jp__byulstar" },
  { name: "江南リスリム医院", account: "@RESLIMCLINIC" },
  { name: "狎鴎亭トップライン", account: "@aptopline1675" },
  { name: "空間 (GONGGAN) 美容外科", account: "@gongganclinic" },
  { name: "立体美容外科 (Ipche)", account: "@ipchejp" },
  { name: "輪郭の定石 (Rinkou no Teiseki)", account: "@K_contouring" },
  { name: "イルゴンゴン美容外科", account: "@100psjp" },
  { name: "エディション美容外科", account: "@editionprs" }
];

// Perform updates
// 1. Rename 星美容整形外科 -> ビョル美容外科 (Already done in array)
// 2. Rename 韓国イルゴンゴン美容外科 -> イルゴンゴン美容外科 (Already done)
// 3. Rename 韓国エディション整形外科 -> エディション美容外科 (Already done)
// 4. Update ラミチェ美容外科 -> @Lamiche_Japan (Already done)
// 5. Update レアート整形外科 -> @Lesarts_JP (Already done)
// 6. Update ワーナ美容外科 -> @wannaps_jp (Already done)
// 7. Remove 現代美学 (Done: filtered out manually)
// 8. Remove duplicate ライク (Done)
// 9. Remove ラリ美容整形外科 (Done, LAREE is kept)
// 10. LAREE is already @lareeclinic in list.

// Sort by name (Japanese alphabetical order - simple sort)
clinics.sort((a, b) => a.name.localeCompare(b.name, 'ja'));

// Generate formatted string
const output = clinics.map(c => `            { name: "${c.name}", account: "${c.account}" },`).join('\n');
console.log(output);
