        const allClinics = [
            {name: "1mm美容外科", account: "@1mmps_jp"},
            {name: "1パーセント整形外科", account: "@1percentps"},
            {name: "21美容外科", account: "@21psjp"},
            {name: "AB美容外科", account: "@ABPRS_JP"},
            {name: "AND美容整形外科", account: "@and_ps_jp"},
            {name: "AND美容整形外科(目)", account: "@and_ps_eye"},
            {name: "ARC美容整形外科", account: "@ARC_ps_"},
            {name: "BIKAN整形外科", account: "@bikanps"},
            {name: "BN (ビエヌ) 美容外科", account: "@somakisa222"},
            {name: "BNB/バノバギ釜山", account: "@bnbbusan_jp"},
            {name: "BT整形外科", account: "@BTps_jp"},
            {name: "DA美容外科", account: "@daprsjp"},
            {name: "ES清潭", account: "@ES025406042"},
            {name: "EU口腔顎顔面外科", account: "@Eujapan2"},
            {name: "IQ美容整形外科", account: "@iqprsjp"},
            {name: "JAYJUN美容外科", account: "@JAYJUN_PS_JP"},
            {name: "JK美容外科", account: "@jkplasticjp"},
            {name: "JT整形外科", account: "@JTJPps"},
            {name: "KOKO美容外科", account: "@kokopsjp"},
            {name: "K美容整形外科病院", account: "@k_ps_jp"},
            {name: "MANO美容整形外科", account: "@MANO95421454"},
            {name: "MARQ (マーク) 美容外科", account: "@marq_ps_jp"},
            {name: "NoseLab (ノーズラボ)", account: "@korea_glory"},
            {name: "SM整形外科", account: "@SM_official_jp"},
            {name: "SODA (ソーダ) 整形外科", account: "@sodaps_official"},
            {name: "TAKO美容整形外科", account: "@takopsjp"},
            {name: "THE MENTOR整形外科", account: "@mentorjp"},
            {name: "TL美容整形外科", account: "@tlpsjp"},
            {name: "U&U美容外科", account: "@_unups"},
            {name: "UcanB美容外科", account: "@ucanb_ps"},
            {name: "VGベリーグッド美容整形外科", account: "@VgprsJ"},
            {name: "VIBE美容外科", account: "@vibeprs"},
            {name: "WANT美容外科", account: "@wantps_jp"},
            {name: "WOORI (ウリ) 美容外科", account: "@wooripsjp"},
            {name: "W美容整形外科", account: "@wps_jp"},
            {name: "XO美容整形外科", account: "@xops_jp"},
            {name: "id美容クリニック (ID)", account: "@idhospital_jp"},
            {name: "アイフィット整形外科", account: "@eyefit_kr"},
            {name: "アイルミ美容外科", account: "@ilumipsjp"},
            {name: "アウラ美容整形外科", account: "@auraps2024"},
            {name: "アバント (AVANT) 美容外科", account: "@avant_ps_jp"},
            {name: "イウル整形外科", account: "@ieulps_jp"},
            {name: "ウィーバー（ウィバース）", account: "@uversejp"},
            {name: "ウォンジン美容整形外科", account: "@wonjin_jpn"},
            {name: "エイペックス美容整形外科", account: "@apex_surgery"},
            {name: "エートップ (Atop)", account: "@atopseikei"},
            {name: "エービー美容外科", account: "@abps_jp"},
            {name: "オヌル整形外科", account: "@onulpsjapan"},
            {name: "オンユ (ONYU) 美容外科", account: "@onyoops_jp"},
            {name: "ガーネット美容整形外科", account: "@garnetps_jp"},
            {name: "キュービス美容整形外科", account: "@qubis_line"},
            {name: "ギリン(GIRIN)整形外科", account: "@girinps"},
            {name: "クッキー整形外科", account: "@cookiepskorea"},
            {name: "クレア美容整形外科", account: "@clairps_jp"},
            {name: "グナル (Gnal) 美容外科", account: "@gnal_ps_jp"},
            {name: "グランド美容整形外科", account: "@grandpsjp"},
            {name: "ケイアート (K-ART) 整形外科", account: "@kartps3615"},
            {name: "コウォン (Cowon) 整形外科", account: "@prepost1"},
            {name: "コエンミ（旧ソウルクイーン）", account: "@seoulqueen7"},
            {name: "コノピ美容整形外科", account: "@conopi_official"},
            {name: "コーヘン (Cohen) 美容外科", account: "@cohenclinic"},
            {name: "サンキュー美容外科", account: "@thankyoups_jp"},
            {name: "ザビダン (The Vidan)", account: "@thebidanjp"},
            {name: "ザ・プラス美容整形外科", account: "@theplustokyo"},
            {name: "シグネチャー美容外科", account: "@signaturepsps"},
            {name: "シャープ整形外科", account: "@sharpps_jp"},
            {name: "シュガー美容整形外科", account: "@sugarprs"},
            {name: "ジェイジュン美容整形外科", account: "@jayjunps_jp"},
            {name: "ジャスト美容整形外科", account: "@justprsjp"},
            {name: "ジュエリー美容外科", account: "@jewelrypsjapan"},
            {name: "スケッチ整形外科", account: "@Sketch_psjp"},
            {name: "スタイル (STYLE) 整形外科", account: "@styleseikei"},
            {name: "スタート整形外科&ヨンセUP整形病院の案内", account: "@startplasty"},
            {name: "スターライン整形外科", account: "@starlinejp"},
            {name: "ストーリークリニック", account: "@skinbystory_JP"},
            {name: "セギム美容整形", account: "@SaekimJP"},
            {name: "セミン整形外科", account: "@seminpsjapan"},
            {name: "ソジン整形外科", account: "@seojin_ps"},
            {name: "ダビダ美容整形外科", account: "@davidaps_jp"},
            {name: "チョンダムDEAR整形外科", account: "@dearpsjapan"},
            {name: "チョンダムOK整形外科", account: "@okaypsjpn"},
            {name: "チョンダムビョル", account: "@CheongdamStar"},
            {name: "テーラー (Tailor) 美容整形外科", account: "@TAILORPS1"},
            {name: "トップフェイス", account: "@topfacejp"},
            {name: "ドクター美", account: "@drmijp"},
            {name: "ドリーム整形外科", account: "@dream2017japan"},
            {name: "ナナ美容外科", account: "@nanahospital"},
            {name: "ナビ美容整形外科", account: "@NAVI_KOREA_"},
            {name: "ノ・ジョンフン整形外科", account: "@njhpsjp2023"},
            {name: "バイウォン美容外科", account: "@BywonClinic"},
            {name: "バノバギ美容整形外科", account: "@banobagi_jp"},
            {name: "バランスラボ（ユーライン）", account: "@ulineclinic"},
            {name: "バンニ美容外科", account: "@vannypsjp"},
            {name: "パステル美容外科", account: "@shimmian_nose"},
            {name: "パラミクリニック", account: "@ParamiClinic"},
            {name: "ヒット (HIT) 整形外科", account: "@hitpsjp"},
            {name: "ビューティーライン整形外科", account: "@beautylinejp"},
            {name: "ビューラベル美容整形外科", account: "@beulibal"},
            {name: "ビュー美容外科", account: "@viewpsjp"},
            {name: "ビリーフ整形外科", account: "@vlif_ps"},
            {name: "ビリーフ美容外科", account: "@vlif_ps"},
            {name: "フィッティング整形外科", account: "@fittingclinicjp"},
            {name: "フェイスプラス整形外科", account: "@faceplusjp"},
            {name: "フェイスライン美容整形外科", account: "@faceline1004"},
            {name: "フルリュン美容外科", account: "@excellent_ps"},
            {name: "フレッシュホンドクター整形外科", account: "@freshps5512"},
            {name: "ブラウン美容外科", account: "@braunpsjp"},
            {name: "プライベート美容外科", account: "@privateps_jp"},
            {name: "プラデン (PLADEN) 美容整形外科", account: "@pladen_jp"},
            {name: "プラネット美容整形外科", account: "@planet_ps_ko"},
            {name: "プリティ美容整形外科", account: "@prettypsjp"},
            {name: "プリンス整形外科", account: "@princepsjp"},
            {name: "プリ美容外科", account: "@vvlyps"},
            {name: "プレミエ美容外科", account: "@PremierPS_JP"},
            {name: "ボムナゲ・ペークリニック", account: "@bbaebbae_jp"},
            {name: "ポップ POP 整形外科", account: "@POPJapanPS"},
            {name: "マイン美容外科", account: "@jpmineplastic"},
            {name: "マーブル美容外科", account: "@marblepsjapan"},
            {name: "ミウ (MIU) 整形外科", account: "@miu_ps_jp"},
            {name: "ミラクル美容整形外科", account: "@miraclelifting"},
            {name: "ユニーク美容整形外科", account: "@unique__jp"},
            {name: "ユノ美容外科", account: "@Yunojp2"},
            {name: "ユボム (UVOM) 整形外科", account: "@uvom_"},
            {name: "ユー&リン美容整形外科", account: "@youandlin_jp"},
            {name: "ユーアンドアイ美容整形外科", account: "@YOUandI_Gangnam"},
            {name: "ヨンセUP整形外科", account: "@YonseiupSeoul"},
            {name: "ライク(LIKE)整形外科", account: "@lps3329"},
            {name: "ライク美容整形外科", account: "@lps3329"},
            {name: "ラインカルチャー", account: "@lineculturejp"},
            {name: "ラミチェ美容外科", account: "@lamichejp"},
            {name: "ラリ美容整形外科", account: "@lari_ps_jp"},
            {name: "リアル美容整形外科", account: "@realps_jp"},
            {name: "リア美容外科", account: "@reapsjp"},
            {name: "リウム（LIMO）", account: "@limops_jpn"},
            {name: "リエンジャン美容外科", account: "@lienjangjp"},
            {name: "リジェン美容整形外科", account: "@regen_ps_jp"},
            {name: "リスペック (Respec) 整形外科", account: "@respectps_jp"},
            {name: "リトマス美容整形外科", account: "@retmusps_jp"},
            {name: "リニュ整形外科", account: "@trnu2019"},
            {name: "リンク美容外科", account: "@kankokuseikei_"},
            {name: "ルジェ美容外科", account: "@lejclinic"},
            {name: "ロウェル美容整形外科", account: "@Lowellprs"},
            {name: "ワナビー美容整形外科", account: "@WANNABE_JPN"},
            {name: "ワンダフル美容外科", account: "@wonderfulpsjpn"},
            {name: "ワーナ美容外科", account: "@wannajpps"},
            {name: "星美容整形外科", account: "@jp__byulstar"},
            {name: "江南HERAクリニック", account: "@gnherajp"},
            {name: "江南リスリム医院", account: "@RESLIMCLINIC"},
            {name: "狎鴎亭トップライン", account: "@aptopline1675"},
            {name: "現代美学", account: "@gendaibigaku_ps"},
            {name: "現代美学美容整形外科", account: "@gendaibigaku_ps"},
            {name: "空間 (GONGGAN) 美容外科", account: "@gongganclinic"},
            {name: "立体美容外科 (Ipche)", account: "@ipchejp"},
            {name: "輪郭の定石 (Rinkou no Teiseki)", account: "@K_contouring"},
            {name: "韓国イルゴンゴン美容外科", account: "@100psjp"},
            {name: "韓国エディション整形外科", account: "@editionprs"},
        ];